matter-labs/vm2

src/callframe.rs, src/fat_pointer.rs, src/heap.rs, src/instruction_handlers/context.rs, src/instruction_handlers/heap_access.rs, src/instruction_handlers/precompiles.rs, src/lib.rs, src/state.rs, src/vm.rs
- use HeapId instead of plain u32
- store heap size as a separate variable to avoid actually allocating u32::MAX for the bootloader
- return that variable from ContextMeta
=> fix: report correct heap sizes in ContextMeta

src/callframe.rs, src/decommit.rs, src/instruction_handlers/context.rs, src/instruction_handlers/event.rs, src/instruction_handlers/precompiles.rs, src/instruction_handlers/ret.rs, src/instruction_handlers/storage.rs, src/lib.rs, src/rollback.rs, src/state.rs, src/vm.rs, src/world_diff.rs
This is accomplished by making pubdata use the same rollback mechanism as everything else.
Another upside is that the total pubdata is now available without having to add together all callframes.
=> fix: revert pubdata on failed near call, too

src/instruction_handlers/precompiles.rs, src/instruction_handlers/storage.rs, src/world_diff.rs
Logs should track the numbers of transactions that they happen in.
=> fix: track transaction number in changes

src/decommit.rs, src/lib.rs, src/testworld.rs, src/world_diff.rs
Previously multivm had to touch DB a lot to figure out whether writes are initial etc. This patch makes all that unnecessary.
Also, the previous version of `get_storage_changes` would have worked incorrectly, had history been deleted. `get_storage_changes_after` does not suffer from the same problem, as the snapshot it consumes guarantees that history after the snapshot exists.
=> fix: don't repeatedly get initial values

Cargo.toml, src/heap.rs
=> feat: exposes necessary methods on heap newtype

src/decommit.rs, src/instruction_handlers/decommit.rs, src/instruction_handlers/ret.rs, src/world_diff.rs
- Tracks `storage_refunds` and `pubdata_costs` in `WorldDiff` in order to fill in the corresponding data in the VM glue code.
- Fixes decommit opcode semantics, refunding extra gas cost if the decommitted bytecode is not fresh (i.e., was decommitted previously).
- `storage_refunds` and `pubdata_costs` data is not read directly on the EN, but is persisted for each batch in the state keeper. By design, this data is expected to filled in by the state keeper, so filling it retrospectively could be a problem.
- Divergency in decommit opcode semantics is easily observable (e.g., by gas costs).
fix: Fix decommit opcode semantics
=> feat: Track `storage_refunds` and `pubdata_costs` stats

src/callframe.rs, src/heap.rs, src/instruction_handlers/decommit.rs, src/instruction_handlers/heap_access.rs, src/instruction_handlers/precompiles.rs, src/single_instruction_test/heap.rs, src/single_instruction_test/stack.rs, src/stack.rs, src/state.rs, src/vm.rs, src/world_diff.rs
The bootloader only uses a small part of the stack and only changes small areas of its heap, yet both are copied entirely when snapshotting. This fixes that.
=> perf: optimize external snapshots

src/heap.rs, src/single_instruction_test/heap.rs, src/state.rs
The aux heap isn't used by the bootloader but tests use it and the bootloader should use it in the future, so this is definitely better.
=> fix: record history for aux heap as well

src/instruction_handlers/near_call.rs, src/single_instruction_test/program.rs
The fuzzer's random program generation was accidentally only generating programs that have instructions everywhere. The data structure had an Option but it was always Some.
Because of this a very simple crash in near call wasn't caught. It is fixed here.
=> fix: fuzzer now makes short programs; fix crash in near call

.github/pull_request_template.md, .github/workflows/ci.yml, Cargo.toml, afl-fuzz/Cargo.toml, src/bitset.rs, src/callframe.rs, src/fat_pointer.rs, src/heap.rs, src/instruction.rs, src/lib.rs, src/program.rs, src/single_instruction_test/program.rs, src/single_instruction_test/stack.rs, src/stack.rs, src/state.rs, src/vm.rs, src/world_diff.rs, tests/bytecode_behaviour.rs, tests/panic.rs, tests/stipend.rs
- Fixes `Heap` equality comparison to allow for additional allocation after a rollback.
- Shortens `Debug` output for large amounts of data (e.g., `Stack`, `Heap`, `Program`) and adds `Debug` impl for a couple of types.
- Equality comparison is used in `zksync_multivm` unit tests.
- More readable `Debug` implementations simplify debugging.
=> fix: Fix `Heap` equality comparison

src/heap.rs, src/instruction_handlers/heap_access.rs, src/single_instruction_test/heap.rs, src/state.rs, src/vm.rs
Another stab to segmented heap, similar to how it's implemented for old VMs (+ recycling heap pages).
Leads to performance improvement compared to the current linear heap design, esp. for single-transaction execution.
=> perf: Implement segmented heap

src/decommit.rs, src/heap.rs
Records a decommitment event even if it would fail with an out-of-gas error.
Reproduces old VM behavior.
=> fix: Fix decommitment logic on out-of-gas

eravm-stable-interface/src/tracer_interface.rs, src/callframe.rs, src/decommit.rs, src/state.rs, src/testworld.rs, src/world_diff.rs, tests/far_call_decommitment.rs, tests/stipend.rs
Fixes decommitment cost divergence introduced after fixing the previous VM divergence.
As of now, bytecode decommitment cost is now not charged even if decommitment failed; this is incorrect. The easiest fix implemented in this PR is to track decommitment status (successful / failed) for all bytecodes.
=> fix: Fix decommitment cost divergence

README.md, crates/vm2-interface/README.md, crates/vm2-interface/src/state_interface.rs, crates/vm2/src/addressing_modes.rs, crates/vm2/src/callframe.rs, crates/vm2/src/decode.rs, crates/vm2/src/heap.rs, crates/vm2/src/instruction_handlers/binop.rs, crates/vm2/src/instruction_handlers/precompiles.rs, crates/vm2/src/lib.rs, crates/vm2/src/program.rs, crates/vm2/src/rollback.rs, crates/vm2/src/single_instruction_test/callframe.rs, crates/vm2/src/single_instruction_test/heap.rs, crates/vm2/src/single_instruction_test/into_zk_evm.rs, crates/vm2/src/single_instruction_test/print_mock_info.rs, crates/vm2/src/single_instruction_test/state_to_zk_evm.rs, crates/vm2/src/single_instruction_test/validation.rs, crates/vm2/src/single_instruction_test/vm.rs, crates/vm2/src/stack.rs, crates/vm2/src/state.rs, crates/vm2/src/tracing.rs, crates/vm2/src/vm.rs, crates/vm2/src/world_diff.rs, crates/vm2/tests/bytecode_behaviour.rs, crates/vm2/tests/far_call_decommitment.rs, crates/vm2/tests/stipend.rs, tests/afl-fuzz/src/show_testcase.rs
Continues brushing up the repo.
- Makes VM state types private and somewhat extends `StateInterface` to compensate.
- Adds some doc comments (more to be added separately).
Minimizes the API surface of the VM crate so that it's easier to maintain.
=> refactor: Brush up repo for publishing (pt. 2)

crates/vm2/src/callframe.rs, crates/vm2/src/instruction_handlers/heap_access.rs, crates/vm2/src/instruction_handlers/mod.rs, crates/vm2/src/instruction_handlers/pointer.rs, crates/vm2/src/instruction_handlers/precompiles.rs, crates/vm2/src/instruction_handlers/ret.rs, crates/vm2/src/single_instruction_test/into_zk_evm.rs, crates/vm2/src/single_instruction_test/print_mock_info.rs, crates/vm2/src/single_instruction_test/state_to_zk_evm.rs, crates/vm2/src/single_instruction_test/vm.rs, crates/vm2/src/state.rs, crates/vm2/src/vm.rs
Fixes a case of unsoundness.
The fix involves a 100% safe Rust way to write generic static variables, so I use it for panic as well.
This may buy us some performance.
=> fix: invalid instruction unsoundness

crates/vm2/src/tracing.rs
StateInterface::current_frame returned the latest far call instead of the latest frame before this fix.
=> fix: StateInterface::current_frame did not work with near calls

crates/vm2/src/tracing.rs
Targeting near calls in the tracer API was very buggy and the code for it was rather convoluted. Both issues are fixed and regression tests are added.
Also fixes an issue where setting the pc would always set the current pc instead of the pc of the targeted frame.
=> fix: some methods operating on wrong near call

.github/workflows/release-please-prepare-branch.yml, .github/workflows/release-please.yml, Cargo.lock
Fixes the release workflow.
The release workflow is currently broken.
=> ci: Brush up repo for publishing – post-release fixes

Cargo.lock, Cargo.toml
Updates the `zk_evm` dependency to the latest published version.
It is impossible to publish the `zksync_vm2` crate which depends on a git revision w/o a version specified.
=> chore: Update `zk_evm` dependency

.github/workflows/ci.yml, crates/vm2/src/lib.rs, crates/vm2/src/single_instruction_test/into_zk_evm.rs, crates/vm2/src/single_instruction_test/world.rs, crates/vm2/src/testonly.rs, crates/vm2/src/world_diff.rs
Replaces storage slot data returned by `StorageInterface` with a dedicated type (essentially, `(U256, bool)`). 
Currently, `StorageInterface` reads storage slots as `Option<U256>` where `None` corresponds to initial writes. This loses information during sandboxed execution. Indeed, there may be slots which have non-zero value, but still are initial writes (i.e., these slots were first written to during previous blocks / transactions in the sandboxed batch).
=> fix!: Revise VM storage interface

crates/vm2-interface/src/lib.rs, crates/vm2-interface/src/state_interface.rs, crates/vm2-interface/src/tracer_interface.rs, crates/vm2/src/callframe.rs, crates/vm2/src/instruction_handlers/binop.rs, crates/vm2/src/instruction_handlers/common.rs, crates/vm2/src/instruction_handlers/context.rs, crates/vm2/src/instruction_handlers/event.rs, crates/vm2/src/instruction_handlers/far_call.rs, crates/vm2/src/instruction_handlers/heap_access.rs, crates/vm2/src/instruction_handlers/jump.rs, crates/vm2/src/instruction_handlers/near_call.rs, crates/vm2/src/instruction_handlers/nop.rs, crates/vm2/src/instruction_handlers/pointer.rs, crates/vm2/src/instruction_handlers/precompiles.rs, crates/vm2/src/instruction_handlers/ret.rs, crates/vm2/src/instruction_handlers/storage.rs, crates/vm2/src/single_instruction_test/callframe.rs, crates/vm2/src/single_instruction_test/print_mock_info.rs, crates/vm2/src/single_instruction_test/program.rs, crates/vm2/src/single_instruction_test/state_to_zk_evm.rs, crates/vm2/src/state.rs, crates/vm2/src/tracing.rs, crates/vm2/src/world_diff.rs
Tracers can now read storage slots. This is required for the validation tracer.
=> feat: expose storage to tracers

crates/vm2/src/instruction_handlers/far_call.rs, crates/vm2/src/instruction_handlers/ret.rs, crates/vm2/src/program.rs, crates/vm2/src/single_instruction_test/program.rs, crates/vm2/src/tests/mod.rs, crates/vm2/src/tests/trace_failing_far_call.rs
Fixes tracing so that a failed far call reports a far call and then a panic to tracers instead of reporting the panic in the middle of the far call.
=> fix: failing far call tracing

.github/workflows/pr-title.yml, crates/vm2/src/addressing_modes.rs, crates/vm2/src/instruction_handlers/binop.rs, crates/vm2/src/precompiles/legacy.rs, crates/vm2/src/predication.rs, crates/vm2/src/world_diff.rs
Workflow is not working properly for external collaborators if `github-status-action-v2` is in use, it's unnecessary and should be removed.
=> ci: fix PR title workflow by removing unnecessary check
